### ISSUE TITLE
` ymd_list$getInfo()` inside `final_filter_distinct` crashing session

### ISSUE THREAD

**Issue by zackarno** [r-tidy-remote-sensing/tidyrgee#4]
Howdy very cool stuff on the new filter function in the new branch. I have had a look today and am still wrapping my head around some of the process, but noticed something causing the session to freeze up when trying to run the first example in `aa_tidyverbs.rmd` 

After walking though some debugging, it seems to be the `ymd_list <- ymd_list$getInfo()` call inside the `final_filter_distinct` function which is causing this issue. Thought I would flag it now in hopes of saving some time

**Comment by joshualerickson** [comment]
I'll take a look tonight but looks like it's in the 'date' call. Not sure what's going on... Still need to test.

**Comment by joshualerickson** [comment]
When a IC is too big getInfo() is too much. Works great for AOI's less about the size of a state but not for bigger areas. This would be feature though if you could filter/keep duplicates in earth engine server side... This would make it really fast when filtering instead of `rgee::get_date_ic()` for big areas. Just a thought to remember but not sure how to filter duplicates in code editor... I'll close since we are moving away from that code.
